### PR TITLE
database update

### PR DESCRIPTION
**Pull request by mirko21**
the job_type field should be updated reflecting the last refactoring.... I have updated the SyncMetadataJob, should it be done for CalculateHashJob too?

in it.po, I've found a wrong key, a mass update is needed?

### CODE REVIEW

**Comment by decriptor** [comment]
Thanks. Could you split the translation changes into a different PR?

**Comment by mirko21** [comment]
I've done. another (little) PR wth only translation changes, now is present

**Comment by dkoeb** [comment]
Sorry for the late reply.

Good catch. I missed this one when refactoring the code. Instead of updating the database as suggested we should try to fix this also for future refactorings. Instead of using the full type name of jobs we should introduce some constant names that are independent of namespaces and class names. Instantiation of jobs via names can easily be done by the already introduced IoC container.

**Comment by dkoeb** [comment]
Just sent another PR that fixes the Job issue without introducing a new database version. Thus, the only thing left from this PR is the fix for missing DefaultVersions.

**Comment by decriptor** [comment]
Closing this in favor of the @dkoeb PR https://github.com/mono/f-spot/pull/124

**Pull request closed without merging**
